"""embed_font.py - regenerate source/vplot/text/dejavu_sans_ttf.h from assets/fonts/DejaVuSans.ttf.

vplot renders text only when FreeType has a face, and a face used to mean a file on disk. That is
fine inside this repo, where load_default_face() walks up to assets/fonts, and wrong everywhere
else: a consumer linking vplot as a package got a library that drew perfect axes and silently no
labels, because vplot skips text rather than failing when it has no font. Embedding the default
face removes the failure and pins the metrics matplotlib lays out against.

The bytes are emitted as octal-escaped string literals rather than a {0x00, ...} initializer list:
MSVC compiles 756 KB of initializer list slowly, and octal escapes are exactly three digits so they
cannot swallow a following hex digit the way a two-digit hex escape can. Each literal stays well
inside MSVC's
65535-character limit.

Usage:  python tools/embed_font.py
"""
import pathlib
import sys

# Four source characters per byte, so 4096 bytes is ~16 KB of literal.
CHUNK = 4096
PER_LINE = 24


def main() -> int:
    root = pathlib.Path(__file__).resolve().parent.parent
    ttf = root / "assets" / "fonts" / "DejaVuSans.ttf"
    out = root / "source" / "vplot" / "text" / "dejavu_sans_ttf.h"
    if not ttf.is_file():
        print(f"missing {ttf}", file=sys.stderr)
        return 1

    data = ttf.read_bytes()
    lines = [
        "/*",
        " * dejavu_sans_ttf.h - DejaVu Sans, embedded.",
        " *",
        " * GENERATED by tools/embed_font.py from assets/fonts/DejaVuSans.ttf. Do not edit by hand;",
        " * re-run the script if the font is replaced.",
        " *",
        " * This is the face matplotlib renders with, so embedding it is what lets a linked-in vplot",
        " * reproduce matplotlib's text metrics with no font file, no search path, and no way for a",
        " * consumer to end up with a figure whose labels silently did not draw.",
        " *",
        " * DejaVu Fonts, Bitstream Vera derivative. The licence permits redistribution provided the",
        " * copyright notice is retained; it is kept verbatim in assets/fonts/LICENSE_DEJAVU and",
        " * summarised in THIRD-PARTY-NOTICES.",
        " */",
        "#ifndef VPL_TEXT_DEJAVU_SANS_TTF_H",
        "#define VPL_TEXT_DEJAVU_SANS_TTF_H",
        "",
        "#include <cstddef>",
        "",
        "namespace vpl",
        "{",
        "",
        f"inline constexpr std::size_t kDejaVuSansSize = {len(data)};",
        "",
        "/* Trailing NUL from the literal is not part of the font; kDejaVuSansSize is the length. */",
        "inline constexpr char kDejaVuSans[] =",
    ]

    for start in range(0, len(data), CHUNK):
        chunk = data[start : start + CHUNK]
        for offset in range(0, len(chunk), PER_LINE):
            piece = chunk[offset : offset + PER_LINE]
            body = "".join(f"\\{b:03o}" for b in piece)
            lines.append(f'    "{body}"')
    lines[-1] += ";"

    lines += [
        "",
        "} // namespace vpl",
        "",
        "#endif /* VPL_TEXT_DEJAVU_SANS_TTF_H */",
    ]

    out.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print(f"wrote {out} ({len(data)} font bytes, {len(lines)} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
